config/routes.rb
Template::Application.routes.draw do
  
  resources :section_attachments


  resources :panel_attachments
  resources :item_attachments
  resources :post_attachments

  scope 'administration' do
    resources :contents
    resources :posts
    resources :items
    resources :panels do
      resources :items
    end
    resources :sections
    resources :terms
  end
  
  match "/administration" => "pages#admin", :as => "admin" #"user_root"
#  match "/home" => "pages#index", :as => "website"
  match '/mail' => 'pages#send_mail', :as => :email, :via => :post
  
  get "pages/index"
  get "pages/administration"

  devise_for :users, :path => 'administration/account', :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}
  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "registrations#new"
    get "/administration/account/settings" => "registrations#edit"
  end
  
#  authenticated :user, lambda {|u| u.admin == true} do
#    root :to => "pages#admin", :as => :admin_root
#    match "/home" => "pages#index", :as => "website"
#  end
  
  match "/news" => "pages#news", as: "news"
  match "/about" => "pages#about", as: "about"
  match "/contact" => "pages#contact", as: "contact"
  match "/glossary" => "pages#glossary", as: "glossary"
  match "/term-select" => "pages#term_select"
  match "/term-all" => "pages#term_all"
  match "/search" => "pages#search", as: "search"
  match "/help" => "pages#help", as: "help"
  match "/explore" => "pages#explore", as: "explore"
  match "/expand" => "pages#expand", as: "expand"
  match "/hub/:id" => "pages#hub", as: "hub"
  match "/pdf/:id" => "pages#pdf", as: "pdf"
  match "/story/:id" => "pages#story", as: "story"
  match "/news/:title" => "pages#news_story", as: "news_story"
  match "/crop/:id" => "items#cropping"
  match "/arrange" => "items#arrange"
  match "/hist" => "pages#hist"
  root :to => "pages#index"

end

app/models/section_attachment.rb
class SectionAttachment < ActiveRecord::Base
  attr_accessible :label, :section_upload
  belongs_to :section
  has_attached_file :section_upload
end

app/controllers/section_attachments_controller.rb
class SectionAttachmentsController < ApplicationController
  # GET /section_attachments
  # GET /section_attachments.json
  def index
    @section_attachments = SectionAttachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @section_attachments }
    end
  end

  # GET /section_attachments/1
  # GET /section_attachments/1.json
  def show
    @section_attachment = SectionAttachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @section_attachment }
    end
  end

  # GET /section_attachments/new
  # GET /section_attachments/new.json
  def new
    @section_attachment = SectionAttachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @section_attachment }
    end
  end

  # GET /section_attachments/1/edit
  def edit
    @section_attachment = SectionAttachment.find(params[:id])
  end

  # POST /section_attachments
  # POST /section_attachments.json
  def create
    @section_attachment = SectionAttachment.new(params[:section_attachment])

    respond_to do |format|
      if @section_attachment.save
        format.html { redirect_to @section_attachment, notice: 'Section attachment was successfully created.' }
        format.json { render json: @section_attachment, status: :created, location: @section_attachment }
      else
        format.html { render action: "new" }
        format.json { render json: @section_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /section_attachments/1
  # PUT /section_attachments/1.json
  def update
    @section_attachment = SectionAttachment.find(params[:id])

    respond_to do |format|
      if @section_attachment.update_attributes(params[:section_attachment])
        format.html { redirect_to @section_attachment, notice: 'Section attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @section_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /section_attachments/1
  # DELETE /section_attachments/1.json
  def destroy
    @section_attachment = SectionAttachment.find(params[:id])
    @section_attachment.destroy

    respond_to do |format|
      format.html { redirect_to section_attachments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/section_attachments_helper.rb
module SectionAttachmentsHelper
end

app/views/section_attachments/_form.html.erb
<%= simple_form_for(@section_attachment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/section_attachments/edit.html.erb
<h1>Editing section_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @section_attachment %> |
<%= link_to 'Back', section_attachments_path %>

app/views/section_attachments/index.html.erb
<h1>Listing section_attachments</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @section_attachments.each do |section_attachment| %>
  <tr>
    <td><%= link_to 'Show', section_attachment %></td>
    <td><%= link_to 'Edit', edit_section_attachment_path(section_attachment) %></td>
    <td><%= link_to 'Destroy', section_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Section attachment', new_section_attachment_path %>

app/views/section_attachments/new.html.erb
<h1>New section_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', section_attachments_path %>

app/views/section_attachments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_section_attachment_path(@section_attachment) %> |
<%= link_to 'Back', section_attachments_path %>