config/routes.rb
Template::Application.routes.draw do
  
  resources :section_attachments


  resources :panel_attachments
  resources :item_attachments
  resources :post_attachments

  scope 'administration' do
    resources :contents
    resources :posts
    resources :items
    resources :panels do
      resources :items
    end
    resources :sections
    resources :terms
  end
  
  match "/administration" => "pages#admin", :as => "admin" #"user_root"
#  match "/home" => "pages#index", :as => "website"
  match '/mail' => 'pages#send_mail', :as => :email, :via => :post
  
  get "pages/index"
  get "pages/administration"

  devise_for :users, :path => 'administration/account', :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}
  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "registrations#new"
    get "/administration/account/settings" => "registrations#edit"
  end
  
#  authenticated :user, lambda {|u| u.admin == true} do
#    root :to => "pages#admin", :as => :admin_root
#    match "/home" => "pages#index", :as => "website"
#  end
  
  match "/news" => "pages#news", as: "news"
  match "/about" => "pages#about", as: "about"
  match "/contact" => "pages#contact", as: "contact"
  match "/glossary" => "pages#glossary", as: "glossary"
  match "/term-select" => "pages#term_select"
  match "/term-all" => "pages#term_all"
  match "/search" => "pages#search", as: "search"
  match "/help" => "pages#help", as: "help"
  match "/explore" => "pages#explore", as: "explore"
  match "/expand" => "pages#expand", as: "expand"
  match "/hub/:id" => "pages#hub", as: "hub"
  match "/pdf/:id" => "pages#pdf", as: "pdf"
  match "/story/:id" => "pages#story", as: "story"
  match "/news/:title" => "pages#news_story", as: "news_story"
  match "/crop/:id" => "items#cropping"
  match "/arrange" => "items#arrange"
  match "/hist" => "pages#hist"
  root :to => "pages#index"

end

app/models/item_attachment.rb
class ItemAttachment < ActiveRecord::Base
  attr_accessible :caption, :item_image, :caption_french
  belongs_to :item
  has_attached_file :item_image, :styles => {:display => "500x500>", :thumb => "250x250>", :expanded => "696x254#", :featured => "486x442#", :large => "486x442#", :wide => "486x238#", :small => "238x238#", :tall => "238x486#"}, :default_url => "/assets/empty.png"
  #validates_attachment_size :item_image, :in => 0.megabytes..1.megabytes
end

app/controllers/item_attachments_controller.rb
class ItemAttachmentsController < ApplicationController
  # GET /item_attachments
  # GET /item_attachments.json
  def index
    @item_attachments = ItemAttachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @item_attachments }
    end
  end

  # GET /item_attachments/1
  # GET /item_attachments/1.json
  def show
    @item_attachment = ItemAttachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item_attachment }
    end
  end

  # GET /item_attachments/new
  # GET /item_attachments/new.json
  def new
    @item_attachment = ItemAttachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item_attachment }
    end
  end

  # GET /item_attachments/1/edit
  def edit
    @item_attachment = ItemAttachment.find(params[:id])
  end

  # POST /item_attachments
  # POST /item_attachments.json
  def create
    @item_attachment = ItemAttachment.new(params[:item_attachment])

    respond_to do |format|
      if @item_attachment.save
        format.html { redirect_to @item_attachment, notice: 'Item attachment was successfully created.' }
        format.json { render json: @item_attachment, status: :created, location: @item_attachment }
      else
        format.html { render action: "new" }
        format.json { render json: @item_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /item_attachments/1
  # PUT /item_attachments/1.json
  def update
    @item_attachment = ItemAttachment.find(params[:id])

    respond_to do |format|
      if @item_attachment.update_attributes(params[:item_attachment])
        format.html { redirect_to @item_attachment, notice: 'Item attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_attachments/1
  # DELETE /item_attachments/1.json
  def destroy
    @item_attachment = ItemAttachment.find(params[:id])
    @item_attachment.destroy

    respond_to do |format|
      format.html { redirect_to item_attachments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/item_attachments_helper.rb
module ItemAttachmentsHelper
end

app/views/item_attachments/_form.html.erb
<%= simple_form_for(@item_attachment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :caption %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/item_attachments/edit.html.erb
<h1>Editing item_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_attachment %> |
<%= link_to 'Back', item_attachments_path %>

app/views/item_attachments/index.html.erb
<h1>Listing item_attachments</h1>

<table>
  <tr>
    <th>Caption</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @item_attachments.each do |item_attachment| %>
  <tr>
    <td><%= item_attachment.caption %></td>
    <td><%= link_to 'Show', item_attachment %></td>
    <td><%= link_to 'Edit', edit_item_attachment_path(item_attachment) %></td>
    <td><%= link_to 'Destroy', item_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item attachment', new_item_attachment_path %>

app/views/item_attachments/new.html.erb
<h1>New item_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', item_attachments_path %>

app/views/item_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Caption:</b>
  <%= @item_attachment.caption %>
</p>


<%= link_to 'Edit', edit_item_attachment_path(@item_attachment) %> |
<%= link_to 'Back', item_attachments_path %>