config/routes.rb
Template::Application.routes.draw do
  
  resources :section_attachments


  resources :panel_attachments
  resources :item_attachments
  resources :post_attachments

  scope 'administration' do
    resources :contents
    resources :posts
    resources :items
    resources :panels do
      resources :items
    end
    resources :sections
    resources :terms
  end
  
  match "/administration" => "pages#admin", :as => "admin" #"user_root"
#  match "/home" => "pages#index", :as => "website"
  match '/mail' => 'pages#send_mail', :as => :email, :via => :post
  
  get "pages/index"
  get "pages/administration"

  devise_for :users, :path => 'administration/account', :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}
  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "registrations#new"
    get "/administration/account/settings" => "registrations#edit"
  end
  
#  authenticated :user, lambda {|u| u.admin == true} do
#    root :to => "pages#admin", :as => :admin_root
#    match "/home" => "pages#index", :as => "website"
#  end
  
  match "/news" => "pages#news", as: "news"
  match "/about" => "pages#about", as: "about"
  match "/contact" => "pages#contact", as: "contact"
  match "/glossary" => "pages#glossary", as: "glossary"
  match "/term-select" => "pages#term_select"
  match "/term-all" => "pages#term_all"
  match "/search" => "pages#search", as: "search"
  match "/help" => "pages#help", as: "help"
  match "/explore" => "pages#explore", as: "explore"
  match "/expand" => "pages#expand", as: "expand"
  match "/hub/:id" => "pages#hub", as: "hub"
  match "/pdf/:id" => "pages#pdf", as: "pdf"
  match "/story/:id" => "pages#story", as: "story"
  match "/news/:title" => "pages#news_story", as: "news_story"
  match "/crop/:id" => "items#cropping"
  match "/arrange" => "items#arrange"
  match "/hist" => "pages#hist"
  root :to => "pages#index"

end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
  attr_accessible :caption, :post_image
  belongs_to :post
  has_attached_file :post_image, :styles => {:display => "500x500>", :thumb => "250x250>"}, :default_url => "/assets/empty.png"
end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @post_attachments }
    end
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
    @post_attachment = PostAttachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post_attachment }
    end
  end

  # GET /post_attachments/new
  # GET /post_attachments/new.json
  def new
    @post_attachment = PostAttachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post_attachment }
    end
  end

  # GET /post_attachments/1/edit
  def edit
    @post_attachment = PostAttachment.find(params[:id])
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(params[:post_attachment])

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully created.' }
        format.json { render json: @post_attachment, status: :created, location: @post_attachment }
      else
        format.html { render action: "new" }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /post_attachments/1
  # PUT /post_attachments/1.json
  def update
    @post_attachment = PostAttachment.find(params[:id])

    respond_to do |format|
      if @post_attachment.update_attributes(params[:post_attachment])
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment = PostAttachment.find(params[:id])
    @post_attachment.destroy

    respond_to do |format|
      format.html { redirect_to post_attachments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/views/post_attachments/_form.html.erb
<%= simple_form_for(@post_attachment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :caption %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/post_attachments/edit.html.erb
<h1>Editing post_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_attachment %> |
<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/index.html.erb
<h1>Listing post_attachments</h1>

<table>
  <tr>
    <th>Caption</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @post_attachments.each do |post_attachment| %>
  <tr>
    <td><%= post_attachment.caption %></td>
    <td><%= link_to 'Show', post_attachment %></td>
    <td><%= link_to 'Edit', edit_post_attachment_path(post_attachment) %></td>
    <td><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post attachment', new_post_attachment_path %>

app/views/post_attachments/new.html.erb
<h1>New post_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Caption:</b>
  <%= @post_attachment.caption %>
</p>


<%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> |
<%= link_to 'Back', post_attachments_path %>