config/routes.rb
Template::Application.routes.draw do
  
  resources :section_attachments


  resources :panel_attachments
  resources :item_attachments
  resources :post_attachments

  scope 'administration' do
    resources :contents
    resources :posts
    resources :items
    resources :panels do
      resources :items
    end
    resources :sections
    resources :terms
  end
  
  match "/administration" => "pages#admin", :as => "admin" #"user_root"
#  match "/home" => "pages#index", :as => "website"
  match '/mail' => 'pages#send_mail', :as => :email, :via => :post
  
  get "pages/index"
  get "pages/administration"

  devise_for :users, :path => 'administration/account', :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}
  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "registrations#new"
    get "/administration/account/settings" => "registrations#edit"
  end
  
#  authenticated :user, lambda {|u| u.admin == true} do
#    root :to => "pages#admin", :as => :admin_root
#    match "/home" => "pages#index", :as => "website"
#  end
  
  match "/news" => "pages#news", as: "news"
  match "/about" => "pages#about", as: "about"
  match "/contact" => "pages#contact", as: "contact"
  match "/glossary" => "pages#glossary", as: "glossary"
  match "/term-select" => "pages#term_select"
  match "/term-all" => "pages#term_all"
  match "/search" => "pages#search", as: "search"
  match "/help" => "pages#help", as: "help"
  match "/explore" => "pages#explore", as: "explore"
  match "/expand" => "pages#expand", as: "expand"
  match "/hub/:id" => "pages#hub", as: "hub"
  match "/pdf/:id" => "pages#pdf", as: "pdf"
  match "/story/:id" => "pages#story", as: "story"
  match "/news/:title" => "pages#news_story", as: "news_story"
  match "/crop/:id" => "items#cropping"
  match "/arrange" => "items#arrange"
  match "/hist" => "pages#hist"
  root :to => "pages#index"

end

app/models/panel_attachment.rb
class PanelAttachment < ActiveRecord::Base
  attr_accessible :caption, :panel_image
  belongs_to :panel
  has_attached_file :panel_image, :styles => {:display => "500x500>", :thumb => "250x250>"}, :default_url => "/assets/empty.png"
end

app/controllers/panel_attachments_controller.rb
class PanelAttachmentsController < ApplicationController
  # GET /panel_attachments
  # GET /panel_attachments.json
  def index
    @panel_attachments = PanelAttachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @panel_attachments }
    end
  end

  # GET /panel_attachments/1
  # GET /panel_attachments/1.json
  def show
    @panel_attachment = PanelAttachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @panel_attachment }
    end
  end

  # GET /panel_attachments/new
  # GET /panel_attachments/new.json
  def new
    @panel_attachment = PanelAttachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @panel_attachment }
    end
  end

  # GET /panel_attachments/1/edit
  def edit
    @panel_attachment = PanelAttachment.find(params[:id])
  end

  # POST /panel_attachments
  # POST /panel_attachments.json
  def create
    @panel_attachment = PanelAttachment.new(params[:panel_attachment])

    respond_to do |format|
      if @panel_attachment.save
        format.html { redirect_to @panel_attachment, notice: 'Panel attachment was successfully created.' }
        format.json { render json: @panel_attachment, status: :created, location: @panel_attachment }
      else
        format.html { render action: "new" }
        format.json { render json: @panel_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /panel_attachments/1
  # PUT /panel_attachments/1.json
  def update
    @panel_attachment = PanelAttachment.find(params[:id])

    respond_to do |format|
      if @panel_attachment.update_attributes(params[:panel_attachment])
        format.html { redirect_to @panel_attachment, notice: 'Panel attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @panel_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /panel_attachments/1
  # DELETE /panel_attachments/1.json
  def destroy
    @panel_attachment = PanelAttachment.find(params[:id])
    @panel_attachment.destroy

    respond_to do |format|
      format.html { redirect_to panel_attachments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/panel_attachments_helper.rb
module PanelAttachmentsHelper
end

app/views/panel_attachments/_form.html.erb
<%= simple_form_for(@panel_attachment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :caption %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/panel_attachments/edit.html.erb
<h1>Editing panel_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @panel_attachment %> |
<%= link_to 'Back', panel_attachments_path %>

app/views/panel_attachments/index.html.erb
<h1>Listing panel_attachments</h1>

<table>
  <tr>
    <th>Caption</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @panel_attachments.each do |panel_attachment| %>
  <tr>
    <td><%= panel_attachment.caption %></td>
    <td><%= link_to 'Show', panel_attachment %></td>
    <td><%= link_to 'Edit', edit_panel_attachment_path(panel_attachment) %></td>
    <td><%= link_to 'Destroy', panel_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Panel attachment', new_panel_attachment_path %>

app/views/panel_attachments/new.html.erb
<h1>New panel_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', panel_attachments_path %>

app/views/panel_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Caption:</b>
  <%= @panel_attachment.caption %>
</p>


<%= link_to 'Edit', edit_panel_attachment_path(@panel_attachment) %> |
<%= link_to 'Back', panel_attachments_path %>